### ISSUE TITLE
Forum frontend issue

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest-mapserver/mapserver#105]
From: https://forum.minetest.net/viewtopic.php?p=374182#p374182

```
Hello! Amazing job with the mapserver. I already tried in some public servers like bananaland and it looks amazing. The thing is, I cannot make it work :(. I cloned the repository and compiled from source and it runs great in console

Code: Select all

INFO[0000] Starting mapserver                            version=dev
INFO[0000] Loading colors                                filename=/colors/vanessa.txt prefix=colormapping size=1335774 useLocal=false
INFO[0000] Loading colors                                filename=/colors/advtrains.txt prefix=colormapping size=497 useLocal=false
INFO[0000] Loading colors                                filename=/colors/scifi_nodes.txt prefix=colormapping size=1315 useLocal=false
INFO[0000] Loading colors                                filename=/colors/mcl2_colors.txt prefix=colormapping size=59983 useLocal=false
INFO[0000] Loading colors                                filename=/colors/miles.txt prefix=colormapping size=1289056 useLocal=false
INFO[0000] Loading colors                                filename=/colors/custom.txt prefix=colormapping size=375 useLocal=false
INFO[0000] Migrating database                            filename=mapserver.sqlite prefix=mapobjectdb.sqlite
INFO[0000] Migration completed                           elapsed="626.097µs" prefix=mapobjectdb.sqlite
INFO[0000] Starting http server                          port=8080 webdev=false
INFO[0000] Starting incremental rendering job            LastMtime=1590358954

But the only thing I can see in the web browser in local is: Starting mapserver.... Any idea how to solve this?

I tried minetest 5.2.0 with minetest_game and minetest 5.0.0 with minimal game.

Thanks in advance!
```
@lulivi If you intend to develop/extend the mapserver you can look at the manual:
https://github.com/minetest-mapserver/mapserver/blob/master/doc/dev.md#generate-the-static-files-webserver-vfs
You may just need to run `go generate`

If you just want to render your server-map i suggest to download a release from:
https://github.com/minetest-mapserver/mapserver/releases

**EDIT**: just fyi: "bananaland" doesn't use this mapserver...

**Comment by OgelGames** [comment]
I've actually experienced the pandorabox map failing to load like that occasionally (mostly only in Chrome), but still being able to load it with another browser. Haven't had it happen for a while, but I just thought I'd mention it.

**Comment by BuckarooBanzay** [comment]
> I've actually experienced the pandorabox map failing to load like that occasionally (mostly only in Chrome), but still being able to load it with another browser. Haven't had it happen for a while, but I just thought I'd mention it.

Feel free to post the errors as issues, i'll try to look at them.

**Comment by lulivi** [comment]
Hello. Thank you for your response and sorry for the confusion about the map provider for bananaland!

I cloned the repository following the [build instructions](https://github.com/minetest-mapserver/mapserver/blob/master/doc/building.md), but I'll try the release. My intention is to use it by itself, just for a server that I have.

**Comment by lulivi** [comment]
All right. I found my problem. *Not reading carefully the documentation*. I was using `localhost/8080` instead of `http://127.0.0.1:8080`. Thank you for your time! So far, love the tool!

**Comment by BuckarooBanzay** [comment]
> All right. I found my problem. Not reading carefully the documentation

Welcome to the club :smile: 

> Edit: Actually, in local worked great. But now I'm testing it in the server, and the Starting mapserver.... appears again. Maybe you can tell me anyway of debugging why is happening?

Can you tell me what the debug console of the browser shows you (F12 on firefox for example)?
There _should_ be some errors in there...

Also for your understanding:
In the configuration file `mapserver.json` is a flag called `webdev`, it does the following, depending on the state:

* `true`: uses the local html/js/css assets from the filesystem
* `false`: uses the embedded assets (if any) from the produced binary

My guess is that you didn't compile the frontend assets with `rollup`:

https://github.com/minetest-mapserver/mapserver/blob/f9318993f2cfdd8d1190d7555a8be50689669ea3/Makefile#L40-L41

But that would be my fault, i completely forgot to document that :see_no_evil: 
I'm updating the documentation now...

**Comment by lulivi** [comment]
I got it working finally!
- Running first the `rollup` and then the go generate, go build
- copying the mapserver binarry to the world directory leaving the `webdev` to `false`
it works! Thank you so much for the help, appreciated :)

**Comment by BuckarooBanzay** [comment]
closing, let me know if you run into more issues...
