### ISSUE TITLE
MapServer don't working on Windows 10

### ISSUE THREAD

**Issue by nitro2010** [minetest-mapserver/mapserver#131]
Hello,
I have problem with the latest version on Windows 10.
I can't display map.
I have valid configuration (default settings).

Page is freezing on: "Starting mapserver..."

In console I don't see any errors.

But I see via Chrome Web Browser Dev Tools (testing using private mode, without any extensions):
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8080/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**main.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.**

![image](https://user-images.githubusercontent.com/950663/93928592-d69fdf00-fd1a-11ea-8660-31fa07912127.png)

**Comment by BuckarooBanzay** [comment]
Which binary do you use? I guess you are trying to compile it yourself, is that correct?
If so, check out the part in the dev manual about the virtual file system and how to generate the files for inclusion in the resulting binary: https://github.com/minetest-mapserver/mapserver/blob/master/doc/dev.md#generate-the-static-files-webserver-vfs

**Comment by nitro2010** [comment]
Hello,
I'm used 4.0.2.
I compiled on Ubuntu for all platforms and now it's working.
Thanks for reply.

I leave link to all recompiled mapserver (version: 5b344015544994ba32162805b6b57208e3e3b1b1)

http://www.mediafire.com/file/sp0hnusbz5gxomq/file
