### ISSUE TITLE
js files missing from latest docker image

### ISSUE THREAD

**Issue by ymph** [minetest-mapserver/mapserver#170]
First thank you for this great application.

It seems that in the latest docker image published on docker hub the `bundle.js` file is missing, preventing the map from loading.

Here are some headers returned by curl:

```
$ curl -I 'https://unej-dev.mt.unej.iri-research.org/js/bundle.js'
HTTP/2 404
server: nginx
date: Tue, 27 Apr 2021 11:55:47 GMT
content-type: text/plain; charset=utf-8
content-length: 19
x-content-type-options: nosniff
strict-transport-security: max-age=31536000
```

whereas for main.js:

```
curl -I 'https://unej-dev.mt.unej.iri-research.org/js/main.js'
HTTP/2 200
server: nginx
date: Tue, 27 Apr 2021 11:56:49 GMT
content-type: text/javascript; charset=utf-8
content-length: 519
accept-ranges: bytes
strict-transport-security: max-age=31536000
```
The `4.3` image seems to run ok.

Docker image info:
  * Digest:sha256:30027c21fb36942836772eb499224a7037b0d563a7fccc48965483ee60fe7483
  * pushed April 12 2021
  * https://hub.docker.com/layers/minetestmapserver/mapserver/latest/images/sha256-30027c21fb36942836772eb499224a7037b0d563a7fccc48965483ee60fe7483?context=explore)

**Comment by BuckarooBanzay** [comment]
> First thank you for this great application.

:heart: 

> It seems that in the latest docker image published on docker hub the bundle.js file is missing, preventing the map from loading.

my mistake: i prepared the `master` branch for the frontend-rewrite (#166) and did some partial renovations there, including the move to go 1.16 and the embedfs as "standard" file embedding mechanism.

Looks like the javascript bundling got messed up there (it even included the `node_modules` folder :facepalm:) should work now :+1:

**Comment by ymph** [comment]
Indeed, it works now!

Thank you very much
