### ISSUE TITLE
Mapserver creates empty sqlite file if it does not exist

### ISSUE THREAD

**Issue by PeterNerlich** [minetest-mapserver/mapserver#171]
When starting mapserver with sqlite specified in the world.mt and the map.sqlite missing, mapserver creates it as an empty file and exits. Every subsequent start of itself and also the minetest server (!) the programs crash because they cannot find the expected tables in the seemingly existing database.

**Comment by S-S-X** [comment]
Program termination is what I would expect in that situation (invalid configuration) but `map.sqlite` should not be created.
Error message would be nice.

Quickly browsing through sources and checking docs for used driver it seems like possibly bug in db driver: mode ro should not create anything.

**Comment by BuckarooBanzay** [comment]
>  Error message would be nice.

added :+1: 

> mode ro should not create anything.

the first connection is made in `rw` mode to migrate the `block` table if needed, creating an empty db-file should be the expected case

Anyway: if the `map.sqlite` is missing and should be there (sqlite mode) the program aborts with a ~~friendly~~ message now.

@PeterNerlich how do you run the mapserver? Should i make a bugfix release or do you compile it yourself (or are you even using the docker image?)
I planned to do the next release after the frontend rewrite in any case (whenever that is)

**Comment by PeterNerlich** [comment]
> how do you run the mapserver? Should i make a bugfix release or do you compile it yourself (or are you even using the docker image?)

I currently just run the binary from the release as a service. We don't use sqlite storage in production though, so no need for an extra release.

Found this while trying to automate this setup and make it reproducible, because the services were started to quickly after another that minetest wasn't even at that point yet where the world is initialised.
