### ISSUE TITLE
Train line, border... markers are ignored when almost off the map in browser

### ISSUE THREAD

**Issue by PeterNerlich** [minetest-mapserver/mapserver#177]
SVG polygon points like train line and border markers are ignored when almost out of the left and bottom border of the window or a bunch of pixels out of the top and right border of the window.

- Current behaviour:
  ![image](https://user-images.githubusercontent.com/10530729/119458598-3680d680-bd3d-11eb-90e0-df99eaa23189.png)
- Desired behaviour:
  ![image](https://user-images.githubusercontent.com/10530729/119459415-eeae7f00-bd3d-11eb-849d-41f09746b311.png)

I have not found the place in the code yet where this happens, but I imagine this process:

Train lines and borders are drawn as SVGs, where every marker node placed in the minetest world adds its coordinates to the list of polygon points (which is sorted by the index specified for the marker node). When displaying on the map, it only makes sense to draw those polygons and that part of polygons that is actually inside the window. So, for every polygon point about to be submitted to the SVG, it is first tested to be inside the current viewport, otherwise it is simply ignored.
This means, that train lines can not only be cut if one point is outside the viewport, it also creates fake lines straight between the points where segments in between have been ignored.
*([here the points get put into a list](https://github.com/minetest-mapserver/mapserver/blob/ff16d3b9d76d3a2e266bf3f109bafe1b4ba43650/public/js/map/overlays/TrainlineOverlay.js#L68), [here that is packed into one object for the whole train line](https://github.com/minetest-mapserver/mapserver/blob/master/public/js/map/overlays/TrainlineOverlay.js#L91) and [here that object is put into a "geoJsonLayer"](https://github.com/minetest-mapserver/mapserver/blob/ff16d3b9d76d3a2e266bf3f109bafe1b4ba43650/public/js/map/overlays/TrainlineOverlay.js#L101) – but the ignoring is still missing)*

I propose to instead keep track of the decision for the last point, and if it is different for the current point (meaning we would be about to create a faulty line) to find and add the point where the window border intersects with the line segment between those two markers. Add a bit of an offset depending on where the "inside" of the viewport is, and voila! We still get ghost lines. But they're not in the viewport, and data outside does not uselessly clutter up the DOM.

What we still would miss are polygon segments that pass through the viewport, where both endpoints are outside.

I'm happy to give this implementation a go, if someone can point me to where the culling happens.

**Comment by PeterNerlich** [comment]
Hang on, [Leaflet should do that automatically already](https://leafletjs.com/examples/quick-start/#markers-circles-and-polygons), from all I can tell. do we mess something up somewhere?

Also, we seem to be using 1.6.0 and 1.7.1 was released in September 2020. Maybe this magically goes away switching to the new version?

**Comment by BuckarooBanzay** [comment]
> Hang on, Leaflet should do that automatically already, from all I can tell. do we mess something up somewhere?

The mapobjects get fetched manually for the current viewport range here:
https://github.com/minetest-mapserver/mapserver/blob/ff16d3b9d76d3a2e266bf3f109bafe1b4ba43650/public/js/map/overlays/AbstractGeoJsonOverlay.js#L50-L82

Maybe the bumping the range up to a few viewports would solve the problem :thinking: 

> Also, we seem to be using 1.6.0 and 1.7.1 was released in September 2020. Maybe this magically goes away switching to the new version?

I wanted to upgrade the whole frontend to vuejs in #166 including the leaflet version but haven't gotten anywhere yet :shrug: 

Patching/Fixing the "old" thing is still an option though...

**Comment by PeterNerlich** [comment]
Aaah, I see, that is certainly a problem. I was assuming we had all the data available and filtered out to match, but it is pulled from the nodes that are visible in the viewport.

Could we modify the api to return all associated mapobjects for any within the viewport? So that if we have one waypoint of the line visible, we return everything we know about that line?

**Comment by PeterNerlich** [comment]
At this point I'm kinda wondering whether it would be easier to just remember the lines and borders in the minetest mod and just pull that list for every mapblock in the viewport... Besides, I also already dreamt of tapping directly into the advtrains database to pull the tracks...
