### ISSUE TITLE
4.3.1 no bundle.js

### ISSUE THREAD

**Issue by inpos** [minetest-mapserver/mapserver#184]
Hi!
When open web-map in browser there is only "Starting server".
Browser console show 404 on get bundle.js.

Debian Linux 10 x86_64
Binary build mapserver 4.3.1 from Releases page.

mapserver 4.2 works fine.

**Comment by BuckarooBanzay** [comment]
ugh, you are right, i forgot the build step :facepalm:

anyway: the new version works now: https://github.com/minetest-mapserver/mapserver/releases/tag/4.3.2

Thanks for reporting :+1:

**Comment by inpos** [comment]
Confirm. Thanks.
