### ISSUE TITLE
Docker tags missing

### ISSUE THREAD

**Issue by bmarwell** [minetest-mapserver/mapserver#185]
Hi,

I was using the 4.3 tag,, but no 4.3.1 nor 4.3.2 tags appered.
Just saw "latest" was updated 21 min ago:
https://hub.docker.com/r/minetestmapserver/mapserver/tags

Can you please update your ci/cd chain to tag releases on dockerhub?
Thanks! :)

**Comment by BuckarooBanzay** [comment]
thanks for the report, i pushed `minetestmapserver/mapserver:4.3.2` manually, fixing the pipeline on the next release :+1:
