### ISSUE TITLE
Incremental rendering: What mtime is stored when? Duplicate mtime values?

### ISSUE THREAD

**Issue by mk-pmb** [minetest-mapserver/mapserver#194]
Hi, thanks for making a neat map server for us!

While reading the docs, I wondered:

https://github.com/minetest-mapserver/mapserver/blob/master/doc/incrementalrendering.md

> After that query

Please clarify when this happens:
* Instantly after the query?
* Or after each block that has been processed?
* Or after all blocks have been processed?
* (Or something else?)

> the highest mtime is stored again in the mapserver database.

Please clarify how duplicate mtime values are dealt with:

* Why use time? Does the DB not provide a guaranteed strictly increasing counter?
* Is it the highest mtime of all blocks in the DB? That would obviously skip blocks that were omitted due to the limit clause.
* Is it the highest mtime of all blocks returned from the query? That could skip blocks that share the same mtime but have not been processed, e.g. due to limit clause.

If I were to implement it, to deal with duplicate mtime values, I'd make the mtime check weak (greater or equal) and in addition check that mtime differs from a new column `last_rendered`. After successful render, I'd set `last_rendered` to the mtime that was reported by the blocks scan query.
Had this approac been considered? Then a link to the discussion should be added to the query example section.

**Comment by BuckarooBanzay** [comment]
> Please clarify when this happens:

The new `mtime` is saved in the _mapserver_ database to keep track of the current progress (_not_ the blocks db, this is the one for the mapserver itself)
This happens after all blocks are queried, processed and rendered, here the important part of the rendering step:

Fetching (by last mtime) -> Rendering -> Set newest mtime of the last fetched block
https://github.com/minetest-mapserver/mapserver/blob/fdee02d5f681000a082b1abb22e06fee19f4baf9/tilerendererjob/incremental.go#L27-L45

Here the relevant sql (for sqlite):
https://github.com/minetest-mapserver/mapserver/blob/fdee02d5f681000a082b1abb22e06fee19f4baf9/db/sqlite/sql.go#L3-L9

> Please clarify how duplicate mtime values are dealt with:

Not at all, it is a range-query, everything _greater_ than the previous mtime gets returned

> Why use time? Does the DB not provide a guaranteed strictly increasing counter?

By using the `mtime` of the stored block (the time it was updated/inserted from the minetest engine) it is possible to process
the changed mapblocks in small batches until every maptile is up-to-date

> If I were to implement it, to deal with duplicate mtime values, I'd make the mtime check weak (greater or equal) and in addition check that mtime differs from a new column last_rendered. After successful render, I'd set last_rendered to the mtime that was reported by the blocks scan query.

Uhm, i'm pretty sure i programmed it that way :thinking: 

If you are still curious how this works you can check out the `map.sqlite` and `mapserver.sqlite` files with the `sqlite3` program, if something is still bugging you feel free to ask here... (also: PR's accepted :wink:)

**Comment by BuckarooBanzay** [comment]
closing this, if you have further questions feel free to open another issue
