### ISSUE TITLE
Mineclone2 0.80.1 mapblock-version not supported: 29

### ISSUE THREAD

**Issue by commel** [minetest-mapserver/mapserver#280]
Mapserver 4.5.0 for MineClone2 0.80.1 with Minetest 5.6.1 crashes when a mapblock is not supported:
```
Nov 15 11:03:17 guenther.holarse.de mapserver-linux-x86_64[1371771]: time="2022-11-15T11:03:17+01:00" level=error msg=mapblock-pars err="mapblock-version not supported: 29" x=-17 y=10 z=18
Nov 15 11:03:17 guenther.holarse.de mapserver-linux-x86_64[1371771]: panic: mapblock-version not supported: 29
Nov 15 11:03:17 guenther.holarse.de mapserver-linux-x86_64[1371771]: goroutine 55 [running]:
Nov 15 11:03:17 guenther.holarse.de mapserver-linux-x86_64[1371771]: mapserver/tilerendererjob.initialRender(0xc000194630)
Nov 15 11:03:17 guenther.holarse.de mapserver-linux-x86_64[1371771]:         /app/tilerendererjob/initial.go:24 +0x610
Nov 15 11:03:17 guenther.holarse.de mapserver-linux-x86_64[1371771]: mapserver/tilerendererjob.Job(0xc000194630)
Nov 15 11:03:17 guenther.holarse.de mapserver-linux-x86_64[1371771]:         /app/tilerendererjob/job.go:23 +0xb2
Nov 15 11:03:17 guenther.holarse.de mapserver-linux-x86_64[1371771]: created by main.main
Nov 15 11:03:17 guenther.holarse.de mapserver-linux-x86_64[1371771]:         /app/main.go:68 +0x3e0
```

**Comment by BuckarooBanzay** [comment]
> Mapserver 4.5.0 for MineClone2 0.80.1 with Minetest 5.6.1

Are you sure about the versions?

The `mapserver` did support the new mapblock format in the last release, which is `4.5.0` 😕 

It pulls in the `mapblock-parser`  with version `v0.1.1`:
https://github.com/minetest-mapserver/mapserver/blob/0f7b1988a7df0fd164e5dbe67eb84feafbaa39c5/go.mod#L6

And the parser should support that too in that version:
https://github.com/minetest-go/mapparser/blob/5669a8808c5cfde2ee6a065239854d3f786d498f/parse.go#L23

Can you re-check the versions, this constellation _should_ work...

**Comment by commel** [comment]
Sorry, for the inconvenience! It was a ansible mixup, the old binary was called. Works fine now!
