### ISSUE TITLE
Gray grass when using  with mineclone2 worlds

### ISSUE THREAD

**Issue by Ranko-Saotome** [minetest-mapserver/mapserver#336]

**Comment by BuckarooBanzay** [comment]
https://github.com/minetest-go/colormapping/blob/main/colors/mc2.txt

**Comment by Ranko-Saotome** [comment]
Grass is till gray even with that colors file

**Comment by Ranko-Saotome** [comment]
Dis regard last message i had the colors file symlinked it worked after i moved the file in to the directory
