### ISSUE TITLE
Is there a way to retreive the number of the player online and lag from the mapserver ?

### ISSUE THREAD

**Issue by Rafi594** [minetest-mapserver/mapserver#76]
Is there a way to retreive the number of players and the lag for embedding on a website ? ![image](https://user-images.githubusercontent.com/28735472/71530607-e6ed6f80-28ea-11ea-926f-97013da4b8b1.png)

**Comment by thomasrudin** [comment]
Sure, this can be done in a few ways:

* You could use a websocket-channel and listen for the stats yourself
* I could provide a basic json/rest api so you can poll the values from the mapserver
* I could provide you with a html-snippet with just those stats on it and you could embed it somewhere in an `iframe` on your page

The first option is possible today, the other two need some work, but not that much...

**Comment by thomasrudin** [comment]
Docs: https://github.com/minetest-mapserver/mapserver/blob/master/doc/stats_webfragment.md
