### ISSUE TITLE
Is admin player hidden?

### ISSUE THREAD

**Issue by Elinvention** [minetest-mapserver/mapserver#87]
I can't see where is the admin player. How can I toggle it on?

**Comment by BuckarooBanzay** [comment]
There is a `mapserver_hide_player` priv:

```lua
minetest.register_privilege("mapserver_hide_player", {
	description = "Player is hidden from the map",
	give_to_singleplayer = false
})
```
See: https://github.com/minetest-mapserver/mapserver_mod/blob/master/privs.lua#L2-L5

Maybe you got it somehow through `/grantme all` ... 😕 
If you revoke that priv it should be visible on the map

**Comment by Elinvention** [comment]
Thanks, that answers my question. I couldn't find that in the documentation.

**Comment by BuckarooBanzay** [comment]
Ha! I knew i documented that somewhere (readme.md -> mapserver_mod):
https://github.com/minetest-mapserver/mapserver/blob/master/doc/mod.md#hiding-players-from-the-map

😄 

Closing this, feel free to reopen if you have issues...
